# Generated by Django 4.0.2 on 2023-06-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_at',
            field=models.DateField(auto_now_add=True, verbose_name='joined date'),
        ),
    ]
