# Generated by Django 4.2.2 on 2023-06-13 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user-<django.db.models.fields.related.OneToOneField>/profile/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='born_at',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='birth date'),
        ),
    ]
